### ISSUE TITLE
Error when download data

### ISSUE THREAD

**Issue by lylyjy** [vita-epfl/social-nce#2] opened 2021-03-23 05:52 UTC
When I download data, pip install gdown && gdown https://drive.google.com/uc?id=1D2guAxD_EgrKnJFMcLSBkf10SOagz0mr,
it occurs that:
Traceback (most recent call last):
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f96a64c1100>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1awXDsRQcmgacj7nUhPzwb5UMNZCJCjvu (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96a64c1100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyl/miniconda3/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/gdown/cli.py", line 95, in main
    download(
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/gdown/download.py", line 77, in download
    res = sess.get(url, stream=True)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/lyl/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1awXDsRQcmgacj7nUhPzwb5UMNZCJCjvu (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96a64c1100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

Can you fix it?Thanks.

**Comment by YuejiangLIU** [comment] 2021-03-23 10:21
The error '[Errno 101] Network is unreachable' seems to suggest a network connection problem. As an alternative to the command line, you can also manually download the data from the provided link and place it in the corresponding folder.

**Comment by YuejiangLIU** [comment] 2021-03-24 08:56
I'll close it for now. Please feel free to let me know if you encounter any other problems with the data download.

**Closed as completed by YuejiangLIU** 2021-03-24 08:56 UTC

**Comment by TianleLiu0303** [comment] 2024-12-31 05:26
good job!But I cannot download the dataset

**Comment by EVEREST-dlk** [comment] 2025-03-31 06:15
(social-nce) duanlongkun@duanlongkun-MS-7D89:~/workspace/social-nce-main/crowd_nav/data/demonstration$ gdown https://drive.google.com/uc?id=1D2guAxD_EgrKnJFMcLSBkf10SOagz0mr



Error:

	HTTPSConnectionPool(host='drive.google.com', port=443): Max retries
	exceeded with url: /uc?id=1D2guAxD_EgrKnJFMcLSBkf10SOagz0mr (Caused by
	NewConnectionError('<urllib3.connection.HTTPSConnection object at
	0x78b73cd1ccc0>: Failed to establish a new connection: [Errno 110]
	Connection timed out',))

To report issues, please visit https://github.com/wkentaro/gdown/issues.

The download link for the dataset seems to be closed.
